version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S localhost:8000 -t public
        environment:
            docker: "true"
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
